name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: npm i
      - name: Publish
        uses: cloudflare/wrangler-action@1.2.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
        env:
          APPID: ${{ secrets.APPID }}
          TOKEN: ${{ secrets.TOKEN }}
          PUBLICKEY: ${{ secrets.PUBLICKEY }}
